# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  false
    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  true
    exception:
        codes:
            App\Exception\CustomerNotFound: 404
            App\Exception\PharmacyNotFound: 404
            App\Exception\NotEnoughPoints: 404
        messages:
            App\Exception\CustomerNotFound: true
            App\Exception\PharmacyNotFound: true
            App\Exception\NotEnoughPoints: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
