version: '3'

services:
    database:
        image: postgres:13-alpine
        ports:
            - "5432:5432"
        volumes:
            - pg-dataset:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            -   database
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: root
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8080:80"
volumes:
    pg-dataset: